
/*
 * File 'sysclsstubsfe.cc'
 *
 * Package Name 'syscls'
 *
 * Generated by eyedbodl at Wed Jan 11 20:50:33 2006
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/syscls.h>

using namespace eyedb;

