
/*
 * File 'utilsstubsbe.cc'
 *
 * Package Name 'utils'
 *
 * Generated by eyedbodl at Wed Jan 11 22:41:37 2006
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/utils.h>

using namespace eyedb;

