
/*
 * EyeDB Version 2.7.12 Copyright (c) 1995-2006 SYSRA
 *
 * File 'utilsstubsbe.cc'
 *
 * Package Name 'utils'
 *
 * Generated by eyedbodl at Fri Feb  9 14:05:17 2007
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/utils.h>

using namespace eyedb;

