
/*
 * EyeDB Version 2.7.12 Copyright (c) 1995-2006 SYSRA
 *
 * File 'utilsmthfe-skel.cc'
 *
 * Package Name 'utils'
 *
 * Generated by eyedbodl at Fri Feb  9 14:05:17 2007
 *
 */

#include <eyedb/eyedb.h>

#include "utils.h"

using namespace eyedb;

// To implement and use user methods, perform the following operations
/*

#1. Copy the skeleton file
cp utilsmthfe-skel.cc utilsmthfe.cc

#2. Implement the user methods in utilsmthfe.cc using a text editor

#3. Compile the shared library

#4. Copy the shared library to the eyedb loadable library directory
cp utilsmthfe-2.7.12.so <eyedbinstalldir>/lib/eyedb

#5. Change the file access mode
chmod a+r <eyedbinstalldir>/lib/eyedb/utilsmthfe-2.7.12.so

*/

static Bool __utils_init = False;

#define _packageInit(DB) \
 \
  if (!__utils_init) { \
    utils::init(); \
    __utils_init = True; \
  } \
 \
  if (!(DB)->getUserData("eyedb:utils")) { \
     Status s = utilsDatabase::checkSchema((DB)->getSchema()); \
     if (s) return s; \
     utilsDatabase::setConsApp(DB); \
     (DB)->setUserData("eyedb:utils", (void *)1); \
  }

//
// date* Date::date() [utilsmthfe.cc]
//

Status
__method_static_OUT_date_REF__date_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::date(in date*) [utilsmthfe.cc]
//

Status
__method_static_OUT_date_REF__date_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, Date * d, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::date(in int32) [utilsmthfe.cc]
//

Status
__method_static_OUT_date_REF__date_date__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 julian_day, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::date(in int32, in month, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_date_REF__date_date__IN_int32__IN_month__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 year, const Month::Type m, const eyedblib::int16 day, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::date(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_date_REF__date_date__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * d, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 Date::julian(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_int32_julian_date__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * d, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 Date::year() [utilsmthfe.cc]
//

Status
__method__OUT_int32_year_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::month() [utilsmthfe.cc]
//

Status
__method__OUT_int16_month_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::day() [utilsmthfe.cc]
//

Status
__method__OUT_int16_day_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::day_of_year() [utilsmthfe.cc]
//

Status
__method__OUT_int16_day_of_year_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// month Date::month_of_year() [utilsmthfe.cc]
//

Status
__method__OUT_month_month_of_year_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Month::Type &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// weekday Date::day_of_week() [utilsmthfe.cc]
//

Status
__method__OUT_weekday_day_of_week_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Weekday::Type &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string Date::toString() [utilsmthfe.cc]
//

Status
__method__OUT_string_toString_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_leap_year() [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_leap_year_date(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_equal(in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_equal_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_greater(in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_greater_or_equal(in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_or_equal_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_less(in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_less_or_equal(in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_or_equal_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Date::is_between(in date*, in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_between_date__IN_date_REF___IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d1, Date * d2, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::next(in weekday) [utilsmthfe.cc]
//

Status
__method__OUT_date_REF__next_date__IN_weekday(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Weekday::Type day, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::previous(in weekday) [utilsmthfe.cc]
//

Status
__method__OUT_date_REF__previous_date__IN_weekday(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Weekday::Type day, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::add_days(in int32) [utilsmthfe.cc]
//

Status
__method__OUT_date_REF__add_days_date__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 days, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* Date::substract_days(in int32) [utilsmthfe.cc]
//

Status
__method__OUT_date_REF__substract_days_date__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 days, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 Date::substract_date(in date*) [utilsmthfe.cc]
//

Status
__method__OUT_int32_substract_date_date__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * d, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void Date::set_julian(in int32) [utilsmthfe.cc]
//

Status
__method__OUT_void_set_julian_date__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 julian_day)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void Time::get_local_time_zone(out int16, out int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_void_get_local_time_zone_time__OUT_int16__OUT_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedblib::int16 &tz_hour, eyedblib::int16 &tz_min)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::gmt_time() [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__gmt_time_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::local_time() [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__local_time_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in time*) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, Time * t, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in int64) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int64 usec, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in int64, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_int64__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int64 usec, const eyedblib::int16 tz, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in int16, in int16, in int16, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_int16__IN_int16__IN_int16__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int16 hours, const eyedblib::int16 min, const eyedblib::int16 sec, const eyedblib::int16 msec, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in int16, in int16, in int16, in int16, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int16 hours, const eyedblib::int16 min, const eyedblib::int16 sec, const eyedblib::int16 msec, const eyedblib::int16 usec, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in int16, in int16, in int16, in int16, in int16, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int16 hours, const eyedblib::int16 min, const eyedblib::int16 sec, const eyedblib::int16 msec, const eyedblib::int16 tz_hour, const eyedblib::int16 tz_minute, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in int16, in int16, in int16, in int16, in int16, in int16, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int16 hours, const eyedblib::int16 min, const eyedblib::int16 sec, const eyedblib::int16 msec, const eyedblib::int16 usec, const eyedblib::int16 tz_hour, const eyedblib::int16 tz_minute, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::time(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_REF__time_time__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * t, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int64 Time::usec_time(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_int64_usec_time_time__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * t, eyedblib::int64 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_hour_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_minute_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::second() [utilsmthfe.cc]
//

Status
__method__OUT_int16_second_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::millisecond() [utilsmthfe.cc]
//

Status
__method__OUT_int16_millisecond_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::tz_hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_tz_hour_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::tz_minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_tz_minute_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string Time::toString() [utilsmthfe.cc]
//

Status
__method__OUT_string_toString_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::is_equal(in time*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_equal_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::is_greater(in time*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::is_greater_or_equal(in time*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_or_equal_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::is_less(in time*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::is_less_or_equal(in time*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_or_equal_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::is_between(in time*, in time*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_between_time__IN_time_REF___IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t1, Time * t2, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::add_interval(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_time_REF__add_interval_time__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* Time::substract_interval(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_time_REF__substract_interval_time__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* Time::substract_time(in time*) [utilsmthfe.cc]
//

Status
__method__OUT_time_interval_REF__substract_time_time__IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * t, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::gmt_hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_gmt_hour_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::gmt_minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_gmt_minute_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 Time::microsecond() [utilsmthfe.cc]
//

Status
__method__OUT_int16_microsecond_time(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void Time::set_usecs(in int64, in int16) [utilsmthfe.cc]
//

Status
__method__OUT_void_set_usecs_time__IN_int64__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int64 usecs, const eyedblib::int16 tz)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::gmt_time_stamp() [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__gmt_time_stamp_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::local_time_stamp() [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__local_time_stamp_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in time_stamp*) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, TimeStamp * ts, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in int64) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int64 usec, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in int64, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_int64__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int64 usec, const eyedblib::int16 tz, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in int32, in int64) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_int32__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 julian_day, const eyedblib::int64 usec, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in int32, in int64, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_int32__IN_int64__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 julian_day, const eyedblib::int64 usec, const eyedblib::int16 tz, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in date*, in time*) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_date_REF___IN_time_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, Date * d, Time * t, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in date*) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_date_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, Date * d, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in date*, in int16, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_date_REF___IN_int16__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, Date * d, const eyedblib::int16 tz_hour, const eyedblib::int16 tz_min, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::time_stamp(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_stamp_REF__time_stamp_time_stamp__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * ts, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int64 TimeStamp::usec_time_stamp(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_int64_usec_time_stamp_time_stamp__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * ts, eyedblib::int64 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// date* TimeStamp::date() [utilsmthfe.cc]
//

Status
__method__OUT_date_REF__date_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Date * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time* TimeStamp::time() [utilsmthfe.cc]
//

Status
__method__OUT_time_REF__time_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Time * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 TimeStamp::year() [utilsmthfe.cc]
//

Status
__method__OUT_int32_year_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::month() [utilsmthfe.cc]
//

Status
__method__OUT_int16_month_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::day() [utilsmthfe.cc]
//

Status
__method__OUT_int16_day_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_hour_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_minute_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::second() [utilsmthfe.cc]
//

Status
__method__OUT_int16_second_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::millisecond() [utilsmthfe.cc]
//

Status
__method__OUT_int16_millisecond_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::tz_hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_tz_hour_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::tz_minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_tz_minute_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string TimeStamp::toString() [utilsmthfe.cc]
//

Status
__method__OUT_string_toString_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::plus(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_time_stamp_REF__plus_time_stamp__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_stamp* TimeStamp::minus(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_time_stamp_REF__minus_time_stamp__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, TimeStamp * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::is_equal(in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_equal_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::is_greater(in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::is_greater_or_equal(in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_or_equal_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::is_less(in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::is_less_or_equal(in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_or_equal_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::is_between(in time_stamp*, in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_between_time_stamp__IN_time_stamp_REF___IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts1, TimeStamp * ts2, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::gmt_hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_gmt_hour_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::gmt_minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_gmt_minute_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeStamp::microsecond() [utilsmthfe.cc]
//

Status
__method__OUT_int16_microsecond_time_stamp(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void TimeStamp::set_usecs(in int64, in int16) [utilsmthfe.cc]
//

Status
__method__OUT_void_set_usecs_time_stamp__IN_int64__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int64 usec, const eyedblib::int16 tz)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeStamp::substract(in time_stamp*) [utilsmthfe.cc]
//

Status
__method__OUT_time_interval_REF__substract_time_stamp__IN_time_stamp_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeStamp * ts, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeInterval::time_interval(in int64) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_interval_REF__time_interval_time_interval__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int64 usecs, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeInterval::time_interval(in int32, in int16, in int16, in int16, in int16, in int16) [utilsmthfe.cc]
//

Status
__method_static_OUT_time_interval_REF__time_interval_time_interval__IN_int32__IN_int16__IN_int16__IN_int16__IN_int16__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 day, const eyedblib::int16 hours, const eyedblib::int16 min, const eyedblib::int16 sec, const eyedblib::int16 msec, const eyedblib::int16 usec, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 TimeInterval::day() [utilsmthfe.cc]
//

Status
__method__OUT_int32_day_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::hour() [utilsmthfe.cc]
//

Status
__method__OUT_int16_hour_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::minute() [utilsmthfe.cc]
//

Status
__method__OUT_int16_minute_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::second() [utilsmthfe.cc]
//

Status
__method__OUT_int16_second_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::millisecond() [utilsmthfe.cc]
//

Status
__method__OUT_int16_millisecond_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::microsecond() [utilsmthfe.cc]
//

Status
__method__OUT_int16_microsecond_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::is_zero() [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_zero_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string TimeInterval::toString() [utilsmthfe.cc]
//

Status
__method__OUT_string_toString_time_interval(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeInterval::plus(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_time_interval_REF__plus_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeInterval::minus(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_time_interval_REF__minus_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeInterval::product(in int64) [utilsmthfe.cc]
//

Status
__method__OUT_time_interval_REF__product_time_interval__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int64 val, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// time_interval* TimeInterval::quotient(in int64) [utilsmthfe.cc]
//

Status
__method__OUT_time_interval_REF__quotient_time_interval__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int64 val, TimeInterval * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::is_equal(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_equal_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::is_greater(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::is_greater_or_equal(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_greater_or_equal_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::is_less(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int16 TimeInterval::is_less_or_equal(in time_interval*) [utilsmthfe.cc]
//

Status
__method__OUT_int16_is_less_or_equal_time_interval__IN_time_interval_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, TimeInterval * i, eyedblib::int16 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void TimeInterval::set_usecs(in int64) [utilsmthfe.cc]
//

Status
__method__OUT_void_set_usecs_time_interval__IN_int64(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int64 usecs)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring() [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in string, in int32) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, const eyedblib::int32 offset, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in ostring*) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_ostring_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, OString * s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in char) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_char(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in int32) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ostring(in float) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__ostring_ostring__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::strlen(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_int32_strlen_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::strcmp(in string, in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_int32_strcmp_ostring__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s1, const char * s2, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::strstr(in string, in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_int32_strstr_ostring__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s1, const char * s2, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OString::substr(in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method_static_OUT_string_substr_ostring__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, const eyedblib::int32 offset, const eyedblib::int32 len, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OString::toLower(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_string_toLower_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OString::toUpper(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_string_toUpper_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OString::rtrim(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_string_rtrim_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OString::ltrim(in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_string_ltrim_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::concat(in string, in string) [utilsmthfe.cc]
//

Status
__method_static_OUT_ostring_REF__concat_ostring__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * s1, const char * s2, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::append(in string) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__append_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::append(in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__append_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::append(in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__append_ostring__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 offset, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::prepend(in string) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__prepend_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::prepend(in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__prepend_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::prepend(in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__prepend_ostring__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 offset, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::insert(in int32, in string) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__insert_ostring__IN_int32__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const char * s, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::insert(in int32, in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__insert_ostring__IN_int32__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const char * arg2, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::insert(in int32, in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__insert_ostring__IN_int32__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const char * arg2, const eyedblib::int32 offset2, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::first(in string) [utilsmthfe.cc]
//

Status
__method__OUT_int32_first_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::last(in string) [utilsmthfe.cc]
//

Status
__method__OUT_int32_last_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::find(in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_int32_find_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 offset, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::substr(in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__substr_ostring__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::substr(in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__substr_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * regexp, const eyedblib::int32 offset, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::erase(in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__erase_ostring__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::replace(in int32, in int32, in string) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__replace_ostring__IN_int32__IN_int32__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const eyedblib::int32 len, const char * arg3, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::replace(in int32, in int32, in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__replace_ostring__IN_int32__IN_int32__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const eyedblib::int32 len, const char * arg3, const eyedblib::int32 len2, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::replace(in int32, in int32, in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__replace_ostring__IN_int32__IN_int32__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 offset, const eyedblib::int32 len, const char * arg3, const eyedblib::int32 offset2, const eyedblib::int32 len2, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::replace(in string, in string) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__replace_ostring__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s1, const char * s2, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OString::reset() [utilsmthfe.cc]
//

Status
__method__OUT_void_reset_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::assign(in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__assign_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::assign(in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__assign_ostring__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 offset, const eyedblib::int32 len, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::toLower() [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__toLower_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::toUpper() [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__toUpper_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::rtrim() [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__rtrim_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// ostring* OString::ltrim() [utilsmthfe.cc]
//

Status
__method__OUT_ostring_REF__ltrim_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OString * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::compare(in string) [utilsmthfe.cc]
//

Status
__method__OUT_int32_compare_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::compare(in string, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_int32_compare_ostring__IN_string__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 to, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::compare(in string, in int32, in int32) [utilsmthfe.cc]
//

Status
__method__OUT_int32_compare_ostring__IN_string__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * s, const eyedblib::int32 from, const eyedblib::int32 to, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::is_null() [utilsmthfe.cc]
//

Status
__method__OUT_int32_is_null_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::match(in string) [utilsmthfe.cc]
//

Status
__method__OUT_int32_match_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * regexp, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OString::length() [utilsmthfe.cc]
//

Status
__method__OUT_int32_length_ostring(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string[] OString::split(in string) [utilsmthfe.cc]
//

Status
__method__OUT_string_ARRAY__split_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * separator, char * * &retarg, int &retarg_cnt)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string[] OString::regexp_split(in string) [utilsmthfe.cc]
//

Status
__method__OUT_string_ARRAY__regexp_split_ostring__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * regexp_separator, char * * &retarg, int &retarg_cnt)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

