
/*
 * EyeDB Version 2.7.12 Copyright (c) 1995-2006 SYSRA
 *
 * File 'sysclsstubsfe.cc'
 *
 * Package Name 'syscls'
 *
 * Generated by eyedbodl at Fri Feb  9 14:01:42 2007
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/syscls.h>

using namespace eyedb;

