
/*
 * File 'DBMmthbe-skel.cc'
 *
 * Package Name 'DBM'
 *
 * Generated by eyedbodl at Sat Dec  3 12:43:51 2005
 *
 */

#include <eyedb/eyedb.h>

#include "DBM.h"

using namespace eyedb;

// To implement and use user methods, perform the following operations
/*

#1. Copy the skeleton file
cp DBMmthbe-skel.cc DBMmthbe.cc

#2. Implement the user methods in DBMmthbe.cc using a text editor

#3. Compile the shared library using GNU make
make -f Makefile.DBM all

#4. Copy the shared library to the eyedb loadable library directory
cp DBMmthbe-2.7.0.so $EYEDBROOT/$EYEDBARCH/etc/so/.

#5. Change the file access mode
chmod a+r $EYEDBROOT/$EYEDBARCH/etc/so/DBMmthbe-2.7.0.so

*/

static Bool __DBM_init = False;

#define _packageInit(DB) \
 \
  if (!__DBM_init) { \
    DBM::init(); \
    __DBM_init = True; \
  } \
 \
  if (!(DB)->getUserData("eyedb:DBM")) { \
     Status s = DBMDatabase::checkSchema((DB)->getSchema()); \
     if (s) return s; \
     DBMDatabase::setConsApp(DB); \
     (DB)->setUserData("eyedb:DBM", (void *)1); \
  }

