
/*
 * EyeDB Version 2.8.8 Copyright (c) 1995-2006 SYSRA
 *
 * File 'DBMstubsfe.cc'
 *
 * Package Name 'DBM'
 *
 * Generated by eyedbodl at Thu Sep 10 15:17:07 2009
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include "DBM.h"

using namespace eyedb;

