
/*
 * EyeDB Version 2.8.4 Copyright (c) 1995-2006 SYSRA
 *
 * File 'DBMstubsbe.cc'
 *
 * Package Name 'DBM'
 *
 * Generated by eyedbodl at Fri Jan 18 22:13:24 2008
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include "DBM.h"

using namespace eyedb;

