
/*
 * EyeDB Version 2.8.8 Copyright (c) 1995-2006 SYSRA
 *
 * File 'DBMstubsfe.cc'
 *
 * Package Name 'DBM'
 *
 * Generated by eyedbodl at Mon Apr 12 16:51:37 2010
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include "DBM.h"

using namespace eyedb;

