
/*
 * EyeDB Version 2.7.12 Copyright (c) 1995-2006 SYSRA
 *
 * File 'oqlctbmthfe-skel.cc'
 *
 * Package Name 'oqlctb'
 *
 * Generated by eyedbodl at Fri Feb  9 14:05:26 2007
 *
 */

#include <eyedb/eyedb.h>

#include "oqlctb.h"

using namespace eyedb;

// To implement and use user methods, perform the following operations
/*

#1. Copy the skeleton file
cp oqlctbmthfe-skel.cc oqlctbmthfe.cc

#2. Implement the user methods in oqlctbmthfe.cc using a text editor

#3. Compile the shared library

#4. Copy the shared library to the eyedb loadable library directory
cp oqlctbmthfe-2.7.12.so <eyedbinstalldir>/lib/eyedb

#5. Change the file access mode
chmod a+r <eyedbinstalldir>/lib/eyedb/oqlctbmthfe-2.7.12.so

*/

static Bool __oqlctb_init = False;

#define _packageInit(DB) \
 \
  if (!__oqlctb_init) { \
    oqlctb::init(); \
    __oqlctb_init = True; \
  } \
 \
  if (!(DB)->getUserData("eyedb:oqlctb")) { \
     Status s = oqlctbDatabase::checkSchema((DB)->getSchema()); \
     if (s) return s; \
     oqlctbDatabase::setConsApp(DB); \
     (DB)->setUserData("eyedb:oqlctb", (void *)1); \
  }

//
// oid object::getOid() [oqlctbmthfe.cc]
//

Status
__method__OUT_oid_getOid_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Oid &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// object* object::getObject() [oqlctbmthfe.cc]
//

Status
__method__OUT_object_REF__getObject_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Object * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string object::toString() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_toString_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string object::toString(in int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_toString_object__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 flags, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// database* object::getDatabase() [oqlctbmthfe.cc]
//

Status
__method__OUT_database_REF__getDatabase_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDatabase * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::setDatabase(in database*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDatabase_object__IN_database_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDatabase * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* object::getDataspace() [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDataspace_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::setDataspace(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDataspace_object__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::move(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_move_object__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::store() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_store_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// object* object::clone() [oqlctbmthfe.cc]
//

Status
__method__OUT_object_REF__clone_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Object * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int64 object::getCTime() [oqlctbmthfe.cc]
//

Status
__method__OUT_int64_getCTime_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int64 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int64 object::getMTime() [oqlctbmthfe.cc]
//

Status
__method__OUT_int64_getMTime_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int64 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string object::getStringCTime() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getStringCTime_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string object::getStringMTime() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getStringMTime_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool object::isRemoved() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isRemoved_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool object::isModify() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isModify_object(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::setLock(in lock_mode) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setLock_object__IN_lock_mode(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const OqlCtbLockMode::Type mode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::setLock(in lock_mode, out int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setLock_object__IN_lock_mode__OUT_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const OqlCtbLockMode::Type mode, eyedblib::int32 &rmode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void object::getLock(out lock_mode) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_getLock_object__OUT_lock_mode(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbLockMode::Type &rmode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* class::getDefaultInstanceDataspace() [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDefaultInstanceDataspace_class(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void class::setDefaultInstanceDataspace(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDefaultInstanceDataspace_class__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void class::moveInstances(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_moveInstances_class__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 index::getCount() [oqlctbmthfe.cc]
//

Status
__method__OUT_int32_getCount_index(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* index::getDefaultDataspace() [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDefaultDataspace_index(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void index::setDefaultDataspace(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDefaultDataspace_index__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void index::move(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_move_index__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string index::getImplementation(in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getImplementation_index__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedb::Bool local, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string index::getStats() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getStats_index(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string index::getStats(in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getStats_index__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedb::Bool full, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string index::simulate(in int32, in string, in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_simulate_index__IN_int32__IN_string__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 idxtype, const char * hints, const eyedb::Bool full, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void index::reimplement(in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_reimplement_index__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * hints)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// oid index::reimplement(in int32, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_oid_reimplement_index__IN_int32__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 idxtype, const char * hints, Oid &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 collection::getCount() [oqlctbmthfe.cc]
//

Status
__method__OUT_int32_getCount_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string collection::getName() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getName_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void collection::setName(in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setName_collection__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * name)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool collection::isIn(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isIn_collection__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// oid[] collection::getElements(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_oid_ARRAY__getElements_collection__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj, Oid * &retarg, int &retarg_cnt)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool collection::isLiteral() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isLiteral_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool collection::isPureLiteral() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isPureLiteral_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool collection::isLiteralObject() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isLiteralObject_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void collection::setLiteralObject() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setLiteralObject_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// oid collection::getLiteralOid() [oqlctbmthfe.cc]
//

Status
__method__OUT_oid_getLiteralOid_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, Oid &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* collection::getDefaultDataspace() [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDefaultDataspace_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void collection::setDefaultDataspace(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDefaultDataspace_collection__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void collection::moveElements(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_moveElements_collection__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string collection::getImplementation(in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getImplementation_collection__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedb::Bool local, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string collection::getImplStats() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getImplStats_collection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string collection::getImplStats(in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getImplStats_collection__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedb::Bool full, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string collection::simulate(in int32, in string, in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_string_simulate_collection__IN_int32__IN_string__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 idxtype, const char * hints, const eyedb::Bool full, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void collection::reimplement(in int32, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_reimplement_collection__IN_int32__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 idxtype, const char * hints)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void set::addTo(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_addTo_set__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void set::suppress(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_suppress_set__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void bag::addTo(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_addTo_bag__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void bag::suppress(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_suppress_bag__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void array::setInAt(in int32, in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setInAt_array__IN_int32__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 pos, const Oid obj)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void array::append(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_append_array__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid obj)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void array::suppressAt(in int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_suppressAt_array__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// oid array::retrieveAt(in int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_oid_retrieveAt_array__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 arg1, Oid &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OqlCtbEyedb::getConfigValue(in string) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_string_getConfigValue_eyedb__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, const char * name, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OqlCtbEyedb::getVersion() [oqlctbmthfe.cc]
//

Status
__method_static_OUT_string_getVersion_eyedb(eyedb::Database *_db, eyedb::FEMethod_C *_m, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OqlCtbEyedb::getVersionNumber() [oqlctbmthfe.cc]
//

Status
__method_static_OUT_int32_getVersionNumber_eyedb(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OqlCtbEyedb::getCompilationTime() [oqlctbmthfe.cc]
//

Status
__method_static_OUT_string_getCompilationTime_eyedb(eyedb::Database *_db, eyedb::FEMethod_C *_m, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OqlCtbEyedb::getArchitecture() [oqlctbmthfe.cc]
//

Status
__method_static_OUT_string_getArchitecture_eyedb(eyedb::Database *_db, eyedb::FEMethod_C *_m, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbConnection::open() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_open_connection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbConnection::open(in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_open_connection__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * host, const char * port)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbConnection::close() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_close_connection(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::open(in connection*, in int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_open_database__IN_connection_REF___IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbConnection * conn, const eyedblib::int32 mode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::open(in connection*, in int32, in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_open_database__IN_connection_REF___IN_int32__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbConnection * conn, const eyedblib::int32 mode, const char * userauth, const char * passwdauth)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::open(in int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_open_database__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 mode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::open(in int32, in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_open_database__IN_int32__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 mode, const char * userauth, const char * passwdauth)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::close() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_close_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool OqlCtbDatabase::isAutoPersistMode() [oqlctbmthfe.cc]
//

Status
__method_static_OUT_bool_isAutoPersistMode_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::setAutoPersistMode(in bool) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_void_setAutoPersistMode_database__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedb::Bool arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool OqlCtbDatabase::isDefaultDatabase() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isDefaultDatabase_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::setDefaultDatabase() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDefaultDatabase_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::create() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_create_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::create(in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_create_database__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * userauth, const char * passwdauth)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::destroy() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_destroy_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::destroy(in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_destroy_database__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * userauth, const char * passwdauth)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::rename(in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_rename_database__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * newname)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::rename(in string, in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_rename_database__IN_string__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * newname, const char * userauth, const char * passwdauth)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// connection* OqlCtbDatabase::getConnection() [oqlctbmthfe.cc]
//

Status
__method__OUT_connection_REF__getConnection_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbConnection * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OqlCtbDatabase::getOpenMode() [oqlctbmthfe.cc]
//

Status
__method__OUT_int32_getOpenMode_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool OqlCtbDatabase::getCommitOnClose() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_getCommitOnClose_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::setCommitOnClose(in bool) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setCommitOnClose_database__IN_bool(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedb::Bool arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OqlCtbDatabase::getVersionNumber() [oqlctbmthfe.cc]
//

Status
__method__OUT_int32_getVersionNumber_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// string OqlCtbDatabase::getVersion() [oqlctbmthfe.cc]
//

Status
__method__OUT_string_getVersion_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, char * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::removeObject(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_removeObject_database__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::uncacheObject(in object*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_uncacheObject_database__IN_object_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Object * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::uncacheObject(in oid) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_uncacheObject_database__IN_oid(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::transactionBegin() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_transactionBegin_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::transactionBegin(in int32, in int32, in int32, in int32, in int32, in int32) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_transactionBegin_database__IN_int32__IN_int32__IN_int32__IN_int32__IN_int32__IN_int32(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int32 trsmode, const eyedblib::int32 lockmode, const eyedblib::int32 recovmode, const eyedblib::int32 _magorder, const eyedblib::int32 ratioalrt, const eyedblib::int32 wait_timeout)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::transactionCommit() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_transactionCommit_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::transactionAbort() [oqlctbmthfe.cc]
//

Status
__method__OUT_void_transactionAbort_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// bool OqlCtbDatabase::isInTransaction() [oqlctbmthfe.cc]
//

Status
__method__OUT_bool_isInTransaction_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, eyedb::Bool &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// datafile*[] OqlCtbDatabase::getDatafiles() [oqlctbmthfe.cc]
//

Status
__method__OUT_datafile_REF__ARRAY__getDatafiles_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDatafile * * &retarg, int &retarg_cnt)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// datafile* OqlCtbDatabase::getDatafile(in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_datafile_REF__getDatafile_database__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * name, OqlCtbDatafile * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// datafile* OqlCtbDatabase::getDatafile(in int16) [oqlctbmthfe.cc]
//

Status
__method__OUT_datafile_REF__getDatafile_database__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int16 id, OqlCtbDatafile * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace*[] OqlCtbDatabase::getDataspaces() [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__ARRAY__getDataspaces_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * * &retarg, int &retarg_cnt)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* OqlCtbDatabase::getDataspace(in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDataspace_database__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * name, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* OqlCtbDatabase::getDataspace(in int16) [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDataspace_database__IN_int16(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const eyedblib::int16 id, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// dataspace* OqlCtbDatabase::getDefaultDataspace() [oqlctbmthfe.cc]
//

Status
__method__OUT_dataspace_REF__getDefaultDataspace_database(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::setDefaultDataspace(in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setDefaultDataspace_database__IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, OqlCtbDataspace * arg1)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::moveObjects(in oid[], in dataspace*) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_moveObjects_database__IN_oid_ARRAY___IN_dataspace_REF_(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid *obj, int obj_cnt, OqlCtbDataspace * arg2)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::updateScheme(in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_updateScheme_database__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * odlfile, const char * package)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::updateScheme(in string, in string, in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_updateScheme_database__IN_string__IN_string__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * odlfile, const char * package, const char * schname, const char * db_prefix)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::updateScheme(in string, in string, in string, in string, in string, in string) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_updateScheme_database__IN_string__IN_string__IN_string__IN_string__IN_string__IN_string(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const char * odlfile, const char * package, const char * schname, const char * db_prefix, const char * cpp_cmd, const char * cpp_flags)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::setObjectLock(in oid, in lock_mode) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setObjectLock_database__IN_oid__IN_lock_mode(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid _oid, const OqlCtbLockMode::Type mode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::setObjectLock(in oid, in lock_mode, out lock_mode) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_setObjectLock_database__IN_oid__IN_lock_mode__OUT_lock_mode(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid _oid, const OqlCtbLockMode::Type mode, OqlCtbLockMode::Type &rmode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// void OqlCtbDatabase::getObjectLock(in oid, out lock_mode) [oqlctbmthfe.cc]
//

Status
__method__OUT_void_getObjectLock_database__IN_oid__OUT_lock_mode(eyedb::Database *_db, eyedb::FEMethod_C *_m, eyedb::Object *_o, const Oid _oid, OqlCtbLockMode::Type &rmode)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::acos(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_acos_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::asin(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_asin_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::atan(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_atan_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::atan2(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_atan2_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::cos(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_cos_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::sin(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_sin_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::tan(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_tan_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::cosh(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_cosh_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::sinh(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_sinh_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::tanh(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_tanh_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::exp(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_exp_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::log(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_log_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::log10(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_log10_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::pow(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_pow_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::sqrt(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_sqrt_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::ceil(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_ceil_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::fabs(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_fabs_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::floor(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_floor_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::fmod(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_fmod_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::erf(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_erf_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::erfc(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_erfc_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::gamma(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_gamma_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::hypot(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_hypot_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OqlCtbMath::isnan(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_int32_isnan_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::j0(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_j0_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::j1(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_j1_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::jn(in int32, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_jn_math__IN_int32__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::lgamma(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_lgamma_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::y0(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_y0_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::y1(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_y1_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::yn(in int32, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_yn_math__IN_int32__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const eyedblib::int32 arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::acosh(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_acosh_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::asinh(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_asinh_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::atanh(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_atanh_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::cbrt(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_cbrt_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::logb(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_logb_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::nextafter(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_nextafter_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::remainder(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_remainder_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::scalb(in float, in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_scalb_math__IN_float__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, const double arg2, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::expm1(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_expm1_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// int32 OqlCtbMath::ilogb(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_int32_ilogb_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, eyedblib::int32 &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::log1p(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_log1p_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

//
// float OqlCtbMath::rint(in float) [oqlctbmthfe.cc]
//

Status
__method_static_OUT_float_rint_math__IN_float(eyedb::Database *_db, eyedb::FEMethod_C *_m, const double arg1, double &retarg)
{
  _packageInit(_db);

  //
  // User Implementation
  //

  return eyedb::Success;
}

