
/*
 * EyeDB Version 2.7.12 Copyright (c) 1995-2006 SYSRA
 *
 * File 'oqlctbstubsbe.cc'
 *
 * Package Name 'oqlctb'
 *
 * Generated by eyedbodl at Fri Dec  8 11:02:46 2006
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include "oqlctb.h"

using namespace eyedb;

