
/*
 * File 'sysclsstubsbe.cc'
 *
 * Package Name 'syscls'
 *
 * Generated by eyedbodl at Sat Dec 10 15:43:55 2005
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/syscls.h>

using namespace eyedb;

