
/*
 * File 'sysclsstubsfe.cc'
 *
 * Package Name 'syscls'
 *
 * Generated by eyedbodl at Sat Dec  3 12:43:51 2005
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/syscls.h>

using namespace eyedb;

