
/*
 * EyeDB Version 2.8.8 Copyright (c) 1995-2006 SYSRA
 *
 * File 'sysclsstubsbe.cc'
 *
 * Package Name 'syscls'
 *
 * Generated by eyedbodl at Thu Sep 10 15:17:01 2009
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/syscls.h>

using namespace eyedb;

