
/*
 * EyeDB Version 2.8.8 Copyright (c) 1995-2006 SYSRA
 *
 * File 'utilsstubsbe.cc'
 *
 * Package Name 'utils'
 *
 * Generated by eyedbodl at Thu Sep 10 15:17:13 2009
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/utils.h>

using namespace eyedb;

