
/*
 * EyeDB Version 2.8.8 Copyright (c) 1995-2006 SYSRA
 *
 * File 'utilsstubsbe.cc'
 *
 * Package Name 'utils'
 *
 * Generated by eyedbodl at Wed May 12 11:14:57 2010
 *
 * ---------------------------------------------------
 * -------------- DO NOT EDIT THIS CODE --------------
 * ---------------------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/utils.h>

using namespace eyedb;

