
/*
 * File 'utilsstubsbe.cc'
 *
 * Package Name 'utils'
 *
 * Generated by eyedbodl at Sat Dec  3 12:43:52 2005
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include <eyedb/utils.h>

using namespace eyedb;

