/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eyedb_java_net_unix_UnixSocketImpl */

#ifndef _Included_org_eyedb_java_net_unix_UnixSocketImpl
#define _Included_org_eyedb_java_net_unix_UnixSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eyedb_java_net_unix_UnixSocketImpl
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_eyedb_java_net_unix_UnixSocketImpl_available
  (JNIEnv *, jobject);

/*
 * Class:     org_eyedb_java_net_unix_UnixSocketImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eyedb_java_net_unix_UnixSocketImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     org_eyedb_java_net_unix_UnixSocketImpl
 * Method:    create
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_eyedb_java_net_unix_UnixSocketImpl_create
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_eyedb_java_net_unix_UnixSocketImpl
 * Method:    listen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_eyedb_java_net_unix_UnixSocketImpl_listen
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
