
/*
 * File 'DBMstubsbe.cc'
 *
 * Package Name 'DBM'
 *
 * Generated by eyedbodl at Sat Dec  3 12:43:51 2005
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include "DBM.h"

using namespace eyedb;

