
/*
 * File 'DBMstubsbe.cc'
 *
 * Package Name 'DBM'
 *
 * Generated by eyedbodl at Wed Jan 11 20:56:14 2006
 *
 * -------------------------------------
 * ------- DO NOT EDIT THIS CODE -------
 * -------------------------------------
 *
 */

#include <eyedb/eyedb.h>

#include "DBM.h"

using namespace eyedb;

